---
id: Text_Filter
name: Text_Filter
full: Text filtering and conversion library
description: A library for filtering and converting text.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Text_Filter
authors:
  - name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  - name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  - name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: developer
version:
  release: 3.0.0
  api: 3.0.0alpha1
state:
  release: stable
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^8.1
    composer:
      horde/exception: ^3
      horde/idna: ^2
      horde/util: ^3
      horde/secret: ^3
  optional:
    composer:
      horde/text_flowed: ^3
      horde/translation: ^3
    ext:
      tidy: '*'
  dev:
    composer:
      horde/text_flowed: ^3
      horde/translation: ^3
      horde/util: ^3
vendor: horde
keywords:
  - sanitize
  - html
ci-platform:
  '8.1':
    - php: ^7.4 || ^8
    - ext-dom
    - ext-hash
  '8.2':
    - php: ^7.4 || ^8
    - ext-dom
    - ext-hash
  '8.3':
    - php: ^7.4 || ^8
    - ext-dom
    - ext-hash
  '8.4':
    - php: ^7.4 || ^8
    - ext-dom
    - ext-hash
  '8.5':
    - php: ^7.4 || ^8
    - ext-dom
    - ext-hash
  '8.6':
    - php: ^7.4 || ^8
    - ext-dom
    - ext-hash
ci-platform-flags:
  needs_installer_plugin: false
