---
id: Text_Filter
name: Text_Filter
full: Text filtering and conversion library
description: A library for fitering and converting text.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Text_Filter
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: developer
version:
  release: 3.0.0alpha2
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
      horde/idna: ^2
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
      horde/text_filter_jsmin: ^2
      horde/text_flowed: ^3
      horde/translation: ^3
    ext:
      tidy: '*'
